### PR TITLE
Vindarel/index mention lsp

### PR DESCRIPTION
**Pull request by vindarel**
Hey guys,

I was invited to the lem community (thanks, much obliged),
but I couldn't push a new branch to lem-page's repository.

### CODE REVIEW

**Comment by Sasanidas** [comment]
I see, it happens to me also, I think is @cxxxr who has to add the permissions

**Comment by Sasanidas** [comment]
I guess the new message is not to compare  too much with  GNU Emacs (which we all know and love)

**Comment by vindarel** [comment]
yes, it was also not adding much from the first sentence, and I badly wanted to add a mention about LSP (and three sentences was a bit much).

Guys, this is the beginning of lem-page, there is much to do: 

1. shall we (shall I) send every change with a PR, so they are easier to review
2. or shall we push smallish commits directly to master, bigger commits with a PR (and eventually, merging ourselves), so changes are easier to send. We could build on each other's additions, without prior big plan. If so, I'd see no problems whatsoever if someone reversed or modified my changes afterwards. We could do this until we reach a sufficiently good v1 of the doc.

**Comment by Sasanidas** [comment]
Sure, make sense to me, for example, we can have a list of major modes with a page that explains how to develop in that mode (similar to the wiki documentation but probably in more detail). This can be separate in a branch so we can aggre in the style of it.

Maybe the lsp can be configure from each mode that require.

In any case, thanks for pointing out. I think we can move the conversation to https://github.com/lem-project/lem-page/issues/6

**Comment by cxxxr** [comment]
I guess I was a little short on the permissions, so I made some changes.

**Pull request merged**
